/* ===============================================
>>Compare values from measure exploration by 'Categories'
>> Helps to understand the importance of Categories.
>>Magnitude Analysis = Σ[Measure] BY [Dimension]
=============================================== */
-- use DataWarehouseAnalytics; -- Run this line for connecting with database.


--Find total customers by countries
Select country, count(customer_key) as total_customer
from [gold.dim_customers]
group by country;
-- or we can write:
-- select country, count(*) from [gold.dim_customers] group by country;

-- Find total customers by gender
Select gender, count(customer_key) as total_customer
from [gold.dim_customers]
group by gender;

-- Find total products by category
Select category, count(product_key) as total_product
from [gold.dim_products]
group by category;
-- Find average costs in each category
Select category, avg(cost) as avg_cost
from [gold.dim_products]
group by category;

-- Total revenue generated for each category
Select dp.category, sum(fs.sales_amount) as total_revenue
from [gold.dim_products] dp
left join [gold.fact_sales] fs
on dp.product_key = fs.product_key
group by dp.category
order by total_revenue desc;

-- Total revenue generated by each customer
Select distinct customer_key, sum(sales_amount) as total_revenue
from [gold.fact_sales] 
group by  customer_key
order by total_revenue desc;

-- Distribution of sold items across countries
select dc.country, count(fs.quantity) as total_sold_items
from[gold.dim_customers] dc
left join [gold.fact_sales] fs
on dc.customer_key = fs.customer_key
group by dc.country
order by total_sold_items desc;
